import { v } from "convex/values";
import { query } from "./_generated/server";

/**
 * Static African voiceover catalog mirrored by the GigaEdit web client.
 * No schema change required: queries return seed rows directly.
 */
export const voiceRecordValidator = v.object({
  id: v.string(),
  name: v.string(),
  language: v.string(),
  accent: v.string(),
  region: v.string(),
  flag: v.string(),
  group: v.string(),
  previewText: v.string(),
  provider: v.union(
    v.literal("elevenlabs"),
    v.literal("openai"),
    v.literal("browser"),
    v.literal("device")
  ),
  providerVoiceId: v.string(),
  creditCost: v.number(),
  creditCostGhs: v.number(),
  africanAccent: v.boolean(),
  lang: v.string(),
});

const VOICES = [
  {
    id: "twi_female",
    name: "Ama · Twi",
    language: "Twi",
    accent: "twi",
    region: "Ghana",
    flag: "🇬🇭",
    group: "African",
    previewText: "Akwaaba! Me din de Ama. Mɛka Twi pɛpɛɛpɛ.",
    provider: "elevenlabs" as const,
    providerVoiceId: "twi_female",
    creditCost: 2,
    creditCostGhs: 0.5,
    africanAccent: true,
    lang: "ak-GH",
  },
  {
    id: "twi_male",
    name: "Kwame · Twi",
    language: "Twi",
    accent: "twi",
    region: "Ghana",
    flag: "🇬🇭",
    group: "African",
    previewText: "Maakye! Me din de Kwame. Mɛka Twi ma wo.",
    provider: "browser" as const,
    providerVoiceId: "twi_male",
    creditCost: 0,
    creditCostGhs: 0,
    africanAccent: true,
    lang: "en-GH",
  },
  {
    id: "hausa_female",
    name: "Aisha · Hausa",
    language: "Hausa",
    accent: "hausa",
    region: "Ghana / Nigeria",
    flag: "🇬🇭",
    group: "African",
    previewText: "Sannu! Ni Aisha ce. Ina magana da Hausa cikin salo mai dumi.",
    provider: "elevenlabs" as const,
    providerVoiceId: "hausa_female",
    creditCost: 2,
    creditCostGhs: 0.5,
    africanAccent: true,
    lang: "ha-GH",
  },
  {
    id: "hausa_male",
    name: "Ibrahim · Hausa",
    language: "Hausa",
    accent: "hausa",
    region: "Ghana / Nigeria",
    flag: "🇳🇬",
    group: "African",
    previewText: "Sannu! Ni Ibrahim ne. Ina magana da Hausa.",
    provider: "elevenlabs" as const,
    providerVoiceId: "hausa_male",
    creditCost: 2,
    creditCostGhs: 0.5,
    africanAccent: true,
    lang: "ha-NG",
  },
  {
    id: "ga_female",
    name: "Naa · Ga",
    language: "Ga",
    accent: "ga",
    region: "Ghana",
    flag: "🇬🇭",
    group: "Local",
    previewText: "Ojekoo! Mi lɛ Naa. Mi wɔ Ga wiemɔ lɛ.",
    provider: "openai" as const,
    providerVoiceId: "ga_female",
    creditCost: 2,
    creditCostGhs: 0.4,
    africanAccent: true,
    lang: "en-GH",
  },
  {
    id: "ewe_male",
    name: "Kofi · Ewe",
    language: "Ewe",
    accent: "ewe",
    region: "Ghana / Togo",
    flag: "🇬🇭",
    group: "Local",
    previewText: "Woezɔ! Nye ŋkɔ nye Kofi. Metsɔ Eʋegbe.",
    provider: "openai" as const,
    providerVoiceId: "ewe_male",
    creditCost: 2,
    creditCostGhs: 0.4,
    africanAccent: true,
    lang: "en-GH",
  },
  {
    id: "yoruba_female",
    name: "Adunni · Yoruba",
    language: "Yoruba",
    accent: "yoruba",
    region: "Nigeria",
    flag: "🇳🇬",
    group: "African",
    previewText: "Ẹ kú àárọ̀! Orúkọ mi ni Adunni. Mo ń sọ Yorùbá.",
    provider: "elevenlabs" as const,
    providerVoiceId: "yoruba_female",
    creditCost: 2,
    creditCostGhs: 0.5,
    africanAccent: true,
    lang: "yo-NG",
  },
  {
    id: "swahili_male",
    name: "Juma · Swahili",
    language: "Swahili",
    accent: "swahili",
    region: "East Africa",
    flag: "🇰🇪",
    group: "African",
    previewText: "Habari! Mimi ni Juma. Ninazungumza Kiswahili.",
    provider: "elevenlabs" as const,
    providerVoiceId: "swahili_male",
    creditCost: 2,
    creditCostGhs: 0.5,
    africanAccent: true,
    lang: "sw-KE",
  },
  {
    id: "zulu_female",
    name: "Thandi · Zulu",
    language: "Zulu",
    accent: "zulu",
    region: "South Africa",
    flag: "🇿🇦",
    group: "African",
    previewText: "Sawubona! NginguThandi. Ngikhuluma isiZulu.",
    provider: "openai" as const,
    providerVoiceId: "zulu_female",
    creditCost: 2,
    creditCostGhs: 0.4,
    africanAccent: true,
    lang: "zu-ZA",
  },
  {
    id: "amharic_male",
    name: "Dawit · Amharic",
    language: "Amharic",
    accent: "amharic",
    region: "Ethiopia",
    flag: "🇪🇹",
    group: "African",
    previewText: "ሰላም! እኔ ዳዊት ነኝ። አማርኛ እናገራለሁ።",
    provider: "openai" as const,
    providerVoiceId: "amharic_male",
    creditCost: 3,
    creditCostGhs: 0.4,
    africanAccent: true,
    lang: "am-ET",
  },
  {
    id: "kinyarwanda_female",
    name: "Imena · Kinyarwanda",
    language: "Kinyarwanda",
    accent: "kinyarwanda",
    region: "Rwanda",
    flag: "🇷🇼",
    group: "African",
    previewText: "Muraho! Nitwa Imena. Mvuga Ikinyarwanda.",
    provider: "elevenlabs" as const,
    providerVoiceId: "kinyarwanda_female",
    creditCost: 2,
    creditCostGhs: 0.4,
    africanAccent: true,
    lang: "rw-RW",
  },
  {
    id: "en_gh_female",
    name: "Efua · English (Ghana)",
    language: "English",
    accent: "english",
    region: "Ghana",
    flag: "🇬🇭",
    group: "English",
    previewText: "Hello! I am Efua, speaking English with a Ghanaian accent.",
    provider: "elevenlabs" as const,
    providerVoiceId: "en_gh_female",
    creditCost: 1,
    creditCostGhs: 0.3,
    africanAccent: true,
    lang: "en-GH",
  },
  {
    id: "en_ng_male",
    name: "Tunde · English (Nigeria)",
    language: "English",
    accent: "english",
    region: "Nigeria",
    flag: "🇳🇬",
    group: "English",
    previewText: "Hello! I am Tunde, speaking English with a Nigerian accent.",
    provider: "elevenlabs" as const,
    providerVoiceId: "en_ng_male",
    creditCost: 1,
    creditCostGhs: 0.3,
    africanAccent: true,
    lang: "en-NG",
  },
  {
    id: "device_default",
    name: "On-device voice",
    language: "Device",
    accent: "device",
    region: "Offline · free",
    flag: "📱",
    group: "Local",
    previewText: "Hello! This is your on-device voice preview.",
    provider: "device" as const,
    providerVoiceId: "device_default",
    creditCost: 0,
    creditCostGhs: 0,
    africanAccent: false,
    lang: "en",
  },
] satisfies Array<typeof voiceRecordValidator.type>;

export const listAfricanVoices = query({
  args: {
    accent: v.optional(v.string()),
    group: v.optional(v.string()),
  },
  handler: async (_ctx, args) => {
    return VOICES.filter((voice) => {
      if (args.accent && voice.accent !== args.accent) return false;
      if (args.group && voice.group !== args.group) return false;
      return true;
    });
  },
});

export const getVoiceById = query({
  args: { id: v.string() },
  handler: async (_ctx, args) => VOICES.find((voice) => voice.id === args.id) ?? null,
});

export const listVoices = query({
  args: {},
  handler: async () => VOICES,
});

export const getVoice = query({
  args: { voiceId: v.string() },
  handler: async (_ctx, args) => VOICES.find((voice) => voice.id === args.voiceId) ?? null,
});
