/**
 * Auto-generated by scripts/gigalearn-phase2-generate.mjs — edit the script, not this file.
 */
import type { LearningMediaItem } from "@/lib/gigalearn/mediaLibrary/types";

export const GHANA_PHASE2_VIDEOS: LearningMediaItem[] = [
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 98656,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "video-p2-1",
    "title": "Count with Bananas",
    "description": "Count bananas from one to five with a bright classroom helper. Illustrated storyboard animation for KG1–P2 (original SVG frames + spoken narration).",
    "contentType": "video_story",
    "discoverCategory": "videos-animation",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Animated lessons",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎬",
      "alt": "Count with Bananas animation"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Count bananas from one to five with a bright classroom helper.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-1-f1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 836,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-1-f2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 984,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-1-f3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1160,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-1-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 29609,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-1.mp4",
        "mimeType": "video/mp4",
        "estimatedBytes": 66067,
        "required": false
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 84541,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "video-p2-2",
    "title": "Letter A Adventure",
    "description": "Meet letter A with apple pictures and a clear chant. Illustrated storyboard animation for KG1–P2 (original SVG frames + spoken narration).",
    "contentType": "video_story",
    "discoverCategory": "videos-animation",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Animated lessons",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎬",
      "alt": "Letter A Adventure animation"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Meet letter A with apple pictures and a clear chant.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-2-f1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1003,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-2-f2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1025,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-2-f3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1119,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-2-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 23128,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-2.mp4",
        "mimeType": "video/mp4",
        "estimatedBytes": 58266,
        "required": false
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 70746,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "video-p2-3",
    "title": "Colour Hunt Red",
    "description": "Find red objects around a Ghanaian home. Illustrated storyboard animation for KG1–P2 (original SVG frames + spoken narration).",
    "contentType": "video_story",
    "discoverCategory": "videos-animation",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Animated lessons",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎬",
      "alt": "Colour Hunt Red animation"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Find red objects around a Ghanaian home.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-3-f1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 999,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-3-f2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 999,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-3-f3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 826,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-3-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 21124,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-3.mp4",
        "mimeType": "video/mp4",
        "estimatedBytes": 46798,
        "required": false
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 78705,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "video-p2-4",
    "title": "Shape Circle Clip",
    "description": "Circles everywhere — plates, moons and drums. Illustrated storyboard animation for KG1–P2 (original SVG frames + spoken narration).",
    "contentType": "video_story",
    "discoverCategory": "videos-animation",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Animated lessons",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎬",
      "alt": "Shape Circle Clip animation"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Circles everywhere — plates, moons and drums.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-4-f1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 913,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-4-f2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 821,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-4-f3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 837,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-4-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 22917,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-4.mp4",
        "mimeType": "video/mp4",
        "estimatedBytes": 53217,
        "required": false
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 86868,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "video-p2-5",
    "title": "Body Parts Wave",
    "description": "Wave your hands, stamp your feet, name each part. Illustrated storyboard animation for KG1–P2 (original SVG frames + spoken narration).",
    "contentType": "video_story",
    "discoverCategory": "videos-animation",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Animated lessons",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎬",
      "alt": "Body Parts Wave animation"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Wave your hands, stamp your feet, name each part.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-5-f1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 953,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-5-f2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 971,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-5-f3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 946,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-5-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 25524,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-5.mp4",
        "mimeType": "video/mp4",
        "estimatedBytes": 58474,
        "required": false
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 81556,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "video-p2-6",
    "title": "Market Colours",
    "description": "Walk a bright market and name colours you see. Illustrated storyboard animation for KG1–P2 (original SVG frames + spoken narration).",
    "contentType": "video_story",
    "discoverCategory": "videos-animation",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Animated lessons",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎬",
      "alt": "Market Colours animation"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Walk a bright market and name colours you see.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-6-f1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1230,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-6-f2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 966,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-6-f3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1041,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-6-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 22370,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-6.mp4",
        "mimeType": "video/mp4",
        "estimatedBytes": 55949,
        "required": false
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 76721,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "video-p2-7",
    "title": "Animal Friends Goat",
    "description": "Meet a friendly goat and learn its sound. Illustrated storyboard animation for KG1–P2 (original SVG frames + spoken narration).",
    "contentType": "video_story",
    "discoverCategory": "videos-animation",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Animated lessons",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎬",
      "alt": "Animal Friends Goat animation"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Meet a friendly goat and learn its sound.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-7-f1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1198,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-7-f2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1094,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-7-f3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1306,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-7-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 20683,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-7.mp4",
        "mimeType": "video/mp4",
        "estimatedBytes": 52440,
        "required": false
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 96280,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "video-p2-8",
    "title": "Wash Hands Animation",
    "description": "Soap, water, rinse — a short hygiene storyboard. Illustrated storyboard animation for KG1–P2 (original SVG frames + spoken narration).",
    "contentType": "video_story",
    "discoverCategory": "videos-animation",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Animated lessons",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎬",
      "alt": "Wash Hands Animation animation"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Soap, water, rinse — a short hygiene storyboard.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-8-f1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 970,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-8-f2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1118,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-8-f3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1096,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-8-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 27995,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-8.mp4",
        "mimeType": "video/mp4",
        "estimatedBytes": 65101,
        "required": false
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 68272,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "video-p2-9",
    "title": "Kente Pattern Peek",
    "description": "Watch colour bands appear like woven cloth. Illustrated storyboard animation for KG1–P2 (original SVG frames + spoken narration).",
    "contentType": "video_story",
    "discoverCategory": "videos-animation",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Animated lessons",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎬",
      "alt": "Kente Pattern Peek animation"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Watch colour bands appear like woven cloth.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-9-f1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 842,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-9-f2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 915,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-9-f3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1021,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-9-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 20599,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-9.mp4",
        "mimeType": "video/mp4",
        "estimatedBytes": 44895,
        "required": false
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 86004,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "video-p2-10",
    "title": "River Care Storyboard",
    "description": "Keep rivers clean so fish and families thrive. Illustrated storyboard animation for KG1–P2 (original SVG frames + spoken narration).",
    "contentType": "video_story",
    "discoverCategory": "videos-animation",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Animated lessons",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎬",
      "alt": "River Care Storyboard animation"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Keep rivers clean so fish and families thrive.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-10-f1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1016,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-10-f2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1120,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-10-f3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 992,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-10-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 24188,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/video-p2-10.mp4",
        "mimeType": "video/mp4",
        "estimatedBytes": 58688,
        "required": false
      }
    ]
  }
] as LearningMediaItem[];
