/**
 * Auto-generated by scripts/gigalearn-phase2-generate.mjs — edit the script, not this file.
 */
import type { LearningMediaItem } from "@/lib/gigalearn/mediaLibrary/types";

export const GHANA_PHASE2_GAMES: LearningMediaItem[] = [
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "Original Giga3 educational content for Ghana early years (Phase 2)",
      "rights": "original",
      "reviewed": false
    },
    "id": "game-p2-count-5",
    "title": "Count five mangoes",
    "description": "A short counting game with mangoes for KG1–P1.",
    "contentType": "game",
    "discoverCategory": "games",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Numeracy",
    "topic": "Counting 1–10",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🥭",
      "alt": "Mangoes"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Count the mangoes: one, two, three, four, five.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Count the mangoes: one, two, three, four, five.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "game": {
      "id": "count-5",
      "prompt": "How many mangoes? 🥭🥭🥭🥭🥭",
      "options": [
        "4",
        "5",
        "6"
      ],
      "answer": "5",
      "feedbackCorrect": "Yes! Five mangoes.",
      "feedbackWrong": "Count again slowly."
    }
  }
] as LearningMediaItem[];
