/**
 * Auto-generated by scripts/gigalearn-phase2-generate.mjs — edit the script, not this file.
 */
import type { LearningMediaItem } from "@/lib/gigalearn/mediaLibrary/types";

export const GHANA_PHASE2_SONGS: LearningMediaItem[] = [
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-1",
    "title": "Clap and Count",
    "description": "An original children's song for early years: Clap one, clap two, clap three with me — counting is fun, you will see!",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Clap and Count"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Clap one, clap two, clap three with me — counting is fun, you will see!",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1158,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-1-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 35375,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-1-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-2",
    "title": "Hello Friend",
    "description": "An original children's song for early years: Hello friend, how do you do? I am glad to learn with you.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Hello Friend"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Hello friend, how do you do? I am glad to learn with you.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1154,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-2-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 28301,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-2-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-3",
    "title": "Wash Your Hands",
    "description": "An original children's song for early years: Wash your hands, wash your hands, soap and water, clean again.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Wash Your Hands"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Wash your hands, wash your hands, soap and water, clean again.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1160,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-3-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31161,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-3-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-4",
    "title": "Colours Everywhere",
    "description": "An original children's song for early years: Red and yellow, green and blue — colours shine for me and you.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Colours Everywhere"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Red and yellow, green and blue — colours shine for me and you.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-4.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1166,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-4-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 30515,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-4-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-5",
    "title": "Walk to School",
    "description": "An original children's song for early years: Left and right, step by step, walking to school with pep.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Walk to School"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Left and right, step by step, walking to school with pep.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-5.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1158,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-5-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 30244,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-5-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-6",
    "title": "Thank You Song",
    "description": "An original children's song for early years: Thank you Mama, thank you teacher — gratitude makes kindness richer.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Thank You Song"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Thank you Mama, thank you teacher — gratitude makes kindness richer.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-6.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1158,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-6-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 33151,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-6-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-7",
    "title": "River Fish",
    "description": "An original children's song for early years: Little fish in the river bright, swim along from morning light.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "River Fish"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Little fish in the river bright, swim along from morning light.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-7.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1150,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-7-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 26817,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-7-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-8",
    "title": "Farmers Dig",
    "description": "An original children's song for early years: Dig dig dig, plant plant plant — farmers feed our land.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Farmers Dig"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Dig dig dig, plant plant plant — farmers feed our land.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-8.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1152,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-8-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 28674,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-8-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-9",
    "title": "Good Morning Ghana",
    "description": "An original children's song for early years: Good morning Ghana, skies so blue, we learn and play the whole day through.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Good Morning Ghana"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Good morning Ghana, skies so blue, we learn and play the whole day through.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-9.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1166,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-9-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 36004,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-9-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-10",
    "title": "Share the Ball",
    "description": "An original children's song for early years: Pass the ball, do not grab — sharing makes a happy lab.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Share the Ball"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Pass the ball, do not grab — sharing makes a happy lab.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-10.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1158,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-10-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 27863,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-10-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-11",
    "title": "Alphabet Bounce",
    "description": "An original children's song for early years: A B C, bounce with me — letters dance so playfully.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Alphabet Bounce"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "A B C, bounce with me — letters dance so playfully.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-11.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1160,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-11-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 27601,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-11-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-12",
    "title": "Quiet Time",
    "description": "An original children's song for early years: Soft as cotton, calm and slow — quiet time helps good minds grow.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Quiet Time"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Soft as cotton, calm and slow — quiet time helps good minds grow.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-12.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1150,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-12-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 35887,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-12-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-13",
    "title": "Market Call",
    "description": "An original children's song for early years: Come buy oranges, come buy yam — market songs are Ghana's jam.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Market Call"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Come buy oranges, come buy yam — market songs are Ghana's jam.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-13.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1152,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-13-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31615,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-13-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-14",
    "title": "Brave Little Ant",
    "description": "An original children's song for early years: Ant so small but works so hard — courage lives in every yard.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Brave Little Ant"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Ant so small but works so hard — courage lives in every yard.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-14.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1162,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-14-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31765,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-14-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-15",
    "title": "Evening Prayer Poem Song",
    "description": "An original children's song for early years: Day is done, stars appear — thank you for the friends so dear.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Songs",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎶",
      "alt": "Evening Prayer Poem Song"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Day is done, stars appear — thank you for the friends so dear.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-15.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1178,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-15-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 29456,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-15-q",
      "prompt": "What should we do while singing together?",
      "options": [
        "Listen and join in",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and join in",
      "feedbackCorrect": "Yes — listen and join in kindly.",
      "feedbackWrong": "Try again — songs are better when we listen."
    }
  }
] as LearningMediaItem[];
