/**
 * Auto-generated by scripts/gigalearn-phase2-generate.mjs — edit the script, not this file.
 */
import type { LearningMediaItem } from "@/lib/gigalearn/mediaLibrary/types";

export const GHANA_PHASE2_PICTURES: LearningMediaItem[] = [
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-1",
    "title": "Orange",
    "description": "See orange, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "fruits",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🍊",
      "alt": "Orange"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Orange",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Orange",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1037,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-1-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4886,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-1-g",
      "prompt": "Which one is an orange?",
      "options": [
        "🍊 Orange",
        "🍌 Banana",
        "🍆 Garden egg"
      ],
      "answer": "🍊 Orange",
      "feedbackCorrect": "Yes! That is orange.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-2",
    "title": "Coconut",
    "description": "See coconut, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "fruits",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🥥",
      "alt": "Coconut"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Coconut",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Coconut",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1039,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-2-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 7311,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-2-g",
      "prompt": "Find the coconut.",
      "options": [
        "🥥 Coconut",
        "🍎 Apple",
        "🍇 Grapes"
      ],
      "answer": "🥥 Coconut",
      "feedbackCorrect": "Yes! That is coconut.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-3",
    "title": "Goat",
    "description": "See goat, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "animals-nature",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "animals",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🐐",
      "alt": "Goat"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Goat",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Goat",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 957,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-3-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4367,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-3-g",
      "prompt": "Which animal is a goat?",
      "options": [
        "🐐 Goat",
        "🐈 Cat",
        "🐓 Hen"
      ],
      "answer": "🐐 Goat",
      "feedbackCorrect": "Yes! That is goat.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-4",
    "title": "Hen",
    "description": "See hen, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "animals-nature",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "animals",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🐔",
      "alt": "Hen"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Hen",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Hen",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-4.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 955,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-4-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4208,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-4-g",
      "prompt": "Find the hen.",
      "options": [
        "🐔 Hen",
        "🐕 Dog",
        "🐄 Cow"
      ],
      "answer": "🐔 Hen",
      "feedbackCorrect": "Yes! That is hen.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-5",
    "title": "Red",
    "description": "See red, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "colours",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🟥",
      "alt": "Red"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Red",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Red",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-5.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1031,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-5-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 3895,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-5-g",
      "prompt": "Which colour is red?",
      "options": [
        "🟥 Red",
        "🟦 Blue",
        "🟩 Green"
      ],
      "answer": "🟥 Red",
      "feedbackCorrect": "Yes! That is red.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-6",
    "title": "Blue",
    "description": "See blue, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "colours",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🟦",
      "alt": "Blue"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Blue",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Blue",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-6.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1033,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-6-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4287,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-6-g",
      "prompt": "Pick blue.",
      "options": [
        "🟦 Blue",
        "🟨 Yellow",
        "🟧 Orange"
      ],
      "answer": "🟦 Blue",
      "feedbackCorrect": "Yes! That is blue.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-7",
    "title": "Three",
    "description": "See three, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "numbers-letters",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Numeracy",
    "topic": "numbers",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "3️⃣",
      "alt": "Three"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Three",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Three",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-7.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 828,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-7-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4264,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-7-g",
      "prompt": "How many stones? 🪨🪨🪨",
      "options": [
        "2",
        "3",
        "4"
      ],
      "answer": "3",
      "feedbackCorrect": "Yes! That is three.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-8",
    "title": "Five",
    "description": "See five, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "numbers-letters",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Numeracy",
    "topic": "numbers",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "5️⃣",
      "alt": "Five"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Five",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Five",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-8.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 826,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-8-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5094,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-8-g",
      "prompt": "Count to five.",
      "options": [
        "4",
        "5",
        "6"
      ],
      "answer": "5",
      "feedbackCorrect": "Yes! That is five.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-9",
    "title": "Letter A",
    "description": "See letter a, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "numbers-letters",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "letters",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🅰️",
      "alt": "Letter A"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Letter A",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Letter A",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-9.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 834,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-9-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5846,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-9-g",
      "prompt": "Which letter is A?",
      "options": [
        "A",
        "B",
        "C"
      ],
      "answer": "A",
      "feedbackCorrect": "Yes! That is letter a.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-10",
    "title": "Letter B",
    "description": "See letter b, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "numbers-letters",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "letters",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🅱️",
      "alt": "Letter B"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Letter B",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Letter B",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-10.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 834,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-10-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 6185,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-10-g",
      "prompt": "Find B.",
      "options": [
        "A",
        "B",
        "D"
      ],
      "answer": "B",
      "feedbackCorrect": "Yes! That is letter b.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-11",
    "title": "Circle",
    "description": "See circle, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "shapes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "⭕",
      "alt": "Circle"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Circle",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Circle",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-11.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1037,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-11-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5928,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-11-g",
      "prompt": "Which shape is a circle?",
      "options": [
        "⭕ Circle",
        "⬛ Square",
        "🔺 Triangle"
      ],
      "answer": "⭕ Circle",
      "feedbackCorrect": "Yes! That is circle.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-12",
    "title": "Square",
    "description": "See square, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "shapes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "⬛",
      "alt": "Square"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Square",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Square",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-12.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1037,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-12-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5955,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-12-g",
      "prompt": "Find the square.",
      "options": [
        "⬛ Square",
        "⭕ Circle",
        "⭐ Star"
      ],
      "answer": "⬛ Square",
      "feedbackCorrect": "Yes! That is square.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-13",
    "title": "Hand",
    "description": "See hand, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "body",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "✋",
      "alt": "Hand"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Hand",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Hand",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-13.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1033,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-13-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4260,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-13-g",
      "prompt": "Which is a hand?",
      "options": [
        "✋ Hand",
        "👂 Ear",
        "👃 Nose"
      ],
      "answer": "✋ Hand",
      "feedbackCorrect": "Yes! That is hand.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-14",
    "title": "Eye",
    "description": "See eye, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "body",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👁️",
      "alt": "Eye"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Eye",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Eye",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-14.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1031,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-14-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 3609,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-14-g",
      "prompt": "Find the eye.",
      "options": [
        "👁️ Eye",
        "🦷 Tooth",
        "🦵 Leg"
      ],
      "answer": "👁️ Eye",
      "feedbackCorrect": "Yes! That is eye.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-15",
    "title": "Cup",
    "description": "See cup, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "household",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "☕",
      "alt": "Cup"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Cup",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Cup",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-15.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1031,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-15-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 3585,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-15-g",
      "prompt": "Which is a cup?",
      "options": [
        "☕ Cup",
        "🪑 Chair",
        "🛏️ Bed"
      ],
      "answer": "☕ Cup",
      "feedbackCorrect": "Yes! That is cup.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-16",
    "title": "Chair",
    "description": "See chair, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "household",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🪑",
      "alt": "Chair"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Chair",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Chair",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-16.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1035,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-16-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4417,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-16-g",
      "prompt": "Find the chair.",
      "options": [
        "🪑 Chair",
        "🚪 Door",
        "🪟 Window"
      ],
      "answer": "🪑 Chair",
      "feedbackCorrect": "Yes! That is chair.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-17",
    "title": "Teacher",
    "description": "See teacher, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "occupations",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👩‍🏫",
      "alt": "Teacher"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Teacher",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Teacher",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-17.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1039,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-17-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5226,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-17-g",
      "prompt": "Who helps us learn at school?",
      "options": [
        "Teacher",
        "Pilot",
        "Chef"
      ],
      "answer": "Teacher",
      "feedbackCorrect": "Yes! That is teacher.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-18",
    "title": "Farmer",
    "description": "See farmer, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "occupations",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👩‍🌾",
      "alt": "Farmer"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Farmer",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Farmer",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-18.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1037,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-18-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5197,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-18-g",
      "prompt": "Who grows food on the farm?",
      "options": [
        "Farmer",
        "Driver",
        "Nurse"
      ],
      "answer": "Farmer",
      "feedbackCorrect": "Yes! That is farmer.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-19",
    "title": "River",
    "description": "See river, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "animals-nature",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "environment",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🏞️",
      "alt": "River"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "River",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "River",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-19.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 863,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-19-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4623,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-19-g",
      "prompt": "Where does a fish live?",
      "options": [
        "River",
        "Cupboard",
        "Book"
      ],
      "answer": "River",
      "feedbackCorrect": "Yes! That is river.",
      "feedbackWrong": "Look again carefully."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-20",
    "title": "Tree",
    "description": "See tree, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "animals-nature",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "environment",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🌳",
      "alt": "Tree"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Tree",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Tree",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-20.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 861,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-20-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 3897,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-20-g",
      "prompt": "What gives us shade and fruit?",
      "options": [
        "Tree",
        "Shoe",
        "Phone"
      ],
      "answer": "Tree",
      "feedbackCorrect": "Yes! That is tree.",
      "feedbackWrong": "Look again carefully."
    }
  }
] as LearningMediaItem[];
