/**
 * Auto-generated by scripts/gigalearn-phase2-generate.mjs — edit the script, not this file.
 */
import type { LearningMediaItem } from "@/lib/gigalearn/mediaLibrary/types";

export const GHANA_PHASE2_RHYMES: LearningMediaItem[] = [
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-1",
    "title": "Sunrise Clap",
    "description": "An original nursery rhyme for KG1–P2: Sun up high, clap clap clap. Feet go tip, tip tip tap!",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "☀️",
      "alt": "Sunrise Clap"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Sun up high, clap clap clap. Feet go tip, tip tip tap!",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Sun up high, clap clap clap. Feet go tip, tip tip tap!",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1154,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-1-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31536,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-2",
    "title": "Market Morning",
    "description": "An original nursery rhyme for KG1–P2: To the market we all go, tomatoes red and onions in a row.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🍅",
      "alt": "Market Morning"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "To the market we all go, tomatoes red and onions in a row.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "To the market we all go, tomatoes red and onions in a row.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 930,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-2-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31249,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-3",
    "title": "Rain on Roof",
    "description": "An original nursery rhyme for KG1–P2: Pitter patter on the roof, little drops that tell the truth.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🌧️",
      "alt": "Rain on Roof"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Pitter patter on the roof, little drops that tell the truth.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Pitter patter on the roof, little drops that tell the truth.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1154,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-3-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 27085,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-4",
    "title": "Kind Hands",
    "description": "An original nursery rhyme for KG1–P2: Kind hands help, kind hands share. Kind hands show that we care.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🤝",
      "alt": "Kind Hands"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Kind hands help, kind hands share. Kind hands show that we care.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Kind hands help, kind hands share. Kind hands show that we care.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-4.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 922,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-4-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 34214,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-5",
    "title": "Five Little Goats",
    "description": "An original nursery rhyme for KG1–P2: Five little goats on a dusty hill, one jumps down and four stand still.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🐐",
      "alt": "Five Little Goats"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Five little goats on a dusty hill, one jumps down and four stand still.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Five little goats on a dusty hill, one jumps down and four stand still.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-5.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1164,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-5-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 35932,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-6",
    "title": "Accra Bus",
    "description": "An original nursery rhyme for KG1–P2: Yellow bus, yellow bus, take us safely home to us.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🚌",
      "alt": "Accra Bus"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Yellow bus, yellow bus, take us safely home to us.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Yellow bus, yellow bus, take us safely home to us.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-6.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 920,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-6-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 26091,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-7",
    "title": "Plantain Song Poem",
    "description": "An original nursery rhyme for KG1–P2: Soft plantain, golden brown, sweetest snack in our town.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🍌",
      "alt": "Plantain Song Poem"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Soft plantain, golden brown, sweetest snack in our town.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Soft plantain, golden brown, sweetest snack in our town.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-7.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1166,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-7-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31979,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-8",
    "title": "Clean Teeth",
    "description": "An original nursery rhyme for KG1–P2: Brush up, brush down, smile bright like the sun in town.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "😁",
      "alt": "Clean Teeth"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Brush up, brush down, smile bright like the sun in town.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Brush up, brush down, smile bright like the sun in town.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-8.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 924,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-8-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 28125,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-9",
    "title": "Sharing Water",
    "description": "An original nursery rhyme for KG1–P2: One cup of water, cool and clear — we share with friends who are near.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "💧",
      "alt": "Sharing Water"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "One cup of water, cool and clear — we share with friends who are near.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "One cup of water, cool and clear — we share with friends who are near.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-9.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1156,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-9-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 33762,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 4,
      "maxAge": 5,
      "label": "KG1–KG2 (ages 4–5)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-10",
    "title": "Night Cricket",
    "description": "An original nursery rhyme for KG1–P2: Cricket sings when lights go low, soft goodnight so dreams can grow.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG1",
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🌙",
      "alt": "Night Cricket"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Cricket sings when lights go low, soft goodnight so dreams can grow.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Cricket sings when lights go low, soft goodnight so dreams can grow.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-10.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 928,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-10-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 34735,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-11",
    "title": "School Bag",
    "description": "An original nursery rhyme for KG1–P2: Zip the bag, pack the book, walk to school with a happy look.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎒",
      "alt": "School Bag"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Zip the bag, pack the book, walk to school with a happy look.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Zip the bag, pack the book, walk to school with a happy look.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-11.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1150,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-11-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 29768,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-12",
    "title": "Red Kente Ribbon",
    "description": "An original nursery rhyme for KG1–P2: Red ribbon, gold and green — brightest colours ever seen.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🎀",
      "alt": "Red Kente Ribbon"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Red ribbon, gold and green — brightest colours ever seen.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Red ribbon, gold and green — brightest colours ever seen.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-12.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 934,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-12-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 28151,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-13",
    "title": "Counting Clouds",
    "description": "An original nursery rhyme for KG1–P2: One white cloud, two float by, three soft clouds in a Ghana sky.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "☁️",
      "alt": "Counting Clouds"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "One white cloud, two float by, three soft clouds in a Ghana sky.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "One white cloud, two float by, three soft clouds in a Ghana sky.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-13.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1160,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-13-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 34840,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-14",
    "title": "Honest Heart",
    "description": "An original nursery rhyme for KG1–P2: Tell the truth, be brave and kind — honesty grows a stronger mind.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "💛",
      "alt": "Honest Heart"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Tell the truth, be brave and kind — honesty grows a stronger mind.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Tell the truth, be brave and kind — honesty grows a stronger mind.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-14.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 926,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-14-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 32675,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-15",
    "title": "Little Drum Beat",
    "description": "An original nursery rhyme for KG1–P2: Beat the drum, soft then strong, feel the rhythm all day long.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🥁",
      "alt": "Little Drum Beat"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Beat the drum, soft then strong, feel the rhythm all day long.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Beat the drum, soft then strong, feel the rhythm all day long.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-15.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1162,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-15-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 29653,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-16",
    "title": "Garden Beans",
    "description": "An original nursery rhyme for KG1–P2: Plant the beans, water slow, watch the tiny green leaves grow.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🌱",
      "alt": "Garden Beans"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Plant the beans, water slow, watch the tiny green leaves grow.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Plant the beans, water slow, watch the tiny green leaves grow.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-16.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 926,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-16-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31092,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-17",
    "title": "Friend Beside Me",
    "description": "An original nursery rhyme for KG1–P2: Hand in hand we walk the lane, friendship makes the sunny rain.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👫",
      "alt": "Friend Beside Me"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Hand in hand we walk the lane, friendship makes the sunny rain.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Hand in hand we walk the lane, friendship makes the sunny rain.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-17.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1162,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-17-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 30568,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-18",
    "title": "Mama's Soup",
    "description": "An original nursery rhyme for KG1–P2: Stir the soup, smell the spice, dinner time feels warm and nice.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🍲",
      "alt": "Mama's Soup"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Stir the soup, smell the spice, dinner time feels warm and nice.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Stir the soup, smell the spice, dinner time feels warm and nice.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-18.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 924,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-18-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 32813,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-19",
    "title": "Quiet Listening",
    "description": "An original nursery rhyme for KG1–P2: Ears are open, mouths are still — listening well is a special skill.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👂",
      "alt": "Quiet Listening"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Ears are open, mouths are still — listening well is a special skill.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Ears are open, mouths are still — listening well is a special skill.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-19.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1160,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-19-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31479,
        "required": true
      }
    ]
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 3200,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "rhyme-p2-20",
    "title": "Stars Over Accra",
    "description": "An original nursery rhyme for KG1–P2: Stars above Accra shine, counting sparkles, one to nine.",
    "contentType": "rhyme_song",
    "discoverCategory": "rhymes-poems",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Nursery rhymes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "⭐",
      "alt": "Stars Over Accra"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Stars above Accra shine, counting sparkles, one to nine.",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Stars above Accra shine, counting sparkles, one to nine.",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-20.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 934,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/rhyme-p2-20-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 29918,
        "required": true
      }
    ]
  }
] as LearningMediaItem[];
