/**
 * Auto-generated by scripts/gigalearn-phase2-generate.mjs — edit the script, not this file.
 */
import type { LearningMediaItem } from "@/lib/gigalearn/mediaLibrary/types";

export const GHANA_PHASE2_STORIES: LearningMediaItem[] = [
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 37986,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-1",
    "title": "Ananse and the Sharing Pot",
    "description": "Ananse found a pot of porridge. He learned that sharing made the meal sweeter.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "storytelling",
    "illustration": {
      "kind": "emoji",
      "emoji": "🕷️",
      "alt": "Ananse and the Sharing Pot story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Ananse found a pot of porridge. He learned that sharing made the meal sweeter.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-1-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1331,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-1-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 908,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-1-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 35747,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-1-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 33238,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-2",
    "title": "Ama and the Lost Pencil",
    "description": "Ama told the truth about a lost pencil and found a friend.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "honesty",
    "illustration": {
      "kind": "emoji",
      "emoji": "✏️",
      "alt": "Ama and the Lost Pencil story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Ama told the truth about a lost pencil and found a friend.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-2-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 978,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-2-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 857,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-2-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31403,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-2-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 32330,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-3",
    "title": "Kofi Helps Grandma",
    "description": "Kofi carried water for Grandma and felt proud and kind.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "kindness",
    "illustration": {
      "kind": "emoji",
      "emoji": "💧",
      "alt": "Kofi Helps Grandma story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Kofi carried water for Grandma and felt proud and kind.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-3-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 935,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-3-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1164,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-3-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 30231,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-3-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 35314,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-4",
    "title": "The Market Goat",
    "description": "A curious goat wandered the market until children guided it home.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "everyday",
    "illustration": {
      "kind": "emoji",
      "emoji": "🐐",
      "alt": "The Market Goat story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "A curious goat wandered the market until children guided it home.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-4-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1208,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-4-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1238,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-4-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 32868,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-4-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 32484,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-5",
    "title": "Fati's First Day",
    "description": "Fati was shy on her first school day, then made a new friend.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "friendship",
    "illustration": {
      "kind": "emoji",
      "emoji": "🏫",
      "alt": "Fati's First Day story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Fati was shy on her first school day, then made a new friend.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-5-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 984,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-5-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1061,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-5-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 30439,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-5-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 27639,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-6",
    "title": "The Talking Drum Message",
    "description": "The drum called the village to celebrate a harvest.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "drumming",
    "illustration": {
      "kind": "emoji",
      "emoji": "🥁",
      "alt": "The Talking Drum Message story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "The drum called the village to celebrate a harvest.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-6-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1216,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-6-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1106,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-6-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 25317,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-6-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 34465,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-7",
    "title": "Yaw and the Mango Tree",
    "description": "Yaw waited for mangoes to ripen instead of taking them early.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "honesty",
    "illustration": {
      "kind": "emoji",
      "emoji": "🥭",
      "alt": "Yaw and the Mango Tree story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Yaw waited for mangoes to ripen instead of taking them early.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-7-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1069,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-7-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1027,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-7-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 32369,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-7-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 23886,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-8",
    "title": "Efua's Rainy Walk",
    "description": "Efua shared her umbrella on a rainy Accra walk.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "kindness",
    "illustration": {
      "kind": "emoji",
      "emoji": "☔",
      "alt": "Efua's Rainy Walk story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Efua shared her umbrella on a rainy Accra walk.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-8-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 933,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-8-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1342,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-8-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 21611,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-8-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 26965,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-9",
    "title": "The Honest Fish Seller",
    "description": "A seller returned extra coins and earned trust.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "honesty",
    "illustration": {
      "kind": "emoji",
      "emoji": "🐟",
      "alt": "The Honest Fish Seller story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "A seller returned extra coins and earned trust.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-9-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 980,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-9-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1238,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-9-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 24747,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-9-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 27224,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-10",
    "title": "Little Weaver",
    "description": "A child watched kente threads and learned patience.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "KG2",
      "P1"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "kente weaving",
    "illustration": {
      "kind": "emoji",
      "emoji": "🧵",
      "alt": "Little Weaver story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "A child watched kente threads and learned patience.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-10-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1103,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-10-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1164,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-10-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 24957,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-10-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 25600,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-11",
    "title": "The Kind Class Captain",
    "description": "The captain helped classmates line up fairly.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "friendship",
    "illustration": {
      "kind": "emoji",
      "emoji": "⭐",
      "alt": "The Kind Class Captain story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "The captain helped classmates line up fairly.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-11-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1355,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-11-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 986,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-11-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 23259,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-11-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 31179,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-12",
    "title": "Night Market Lights",
    "description": "Twinkling lamps taught a child to stay close to family.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "everyday",
    "illustration": {
      "kind": "emoji",
      "emoji": "🏮",
      "alt": "Night Market Lights story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Twinkling lamps taught a child to stay close to family.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-12-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1242,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-12-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1026,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-12-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 28911,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-12-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 28295,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-13",
    "title": "Sankofa Bird",
    "description": "A story about looking back to learn and move forward.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "storytelling",
    "illustration": {
      "kind": "emoji",
      "emoji": "🐦",
      "alt": "Sankofa Bird story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "A story about looking back to learn and move forward.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-13-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 943,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-13-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1027,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-13-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 26325,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-13-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 22101,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-14",
    "title": "The Pot Maker's Child",
    "description": "Clay hands shaped a bowl for the family.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "pottery",
    "illustration": {
      "kind": "emoji",
      "emoji": "🏺",
      "alt": "The Pot Maker's Child story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Clay hands shaped a bowl for the family.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-14-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1034,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-14-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 908,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-14-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 20159,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-14-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 27270,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-15",
    "title": "Friends at the Borehole",
    "description": "Children took turns filling buckets without pushing.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "friendship",
    "illustration": {
      "kind": "emoji",
      "emoji": "🚰",
      "alt": "Friends at the Borehole story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Children took turns filling buckets without pushing.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-15-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1072,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-15-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 933,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-15-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 25265,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-15-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 27706,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-16",
    "title": "The Quiet Library",
    "description": "Soft voices helped everyone enjoy story time.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "everyday",
    "illustration": {
      "kind": "emoji",
      "emoji": "📚",
      "alt": "The Quiet Library story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Soft voices helped everyone enjoy story time.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-16-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1141,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-16-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 936,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-16-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 25629,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-16-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 26540,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-17",
    "title": "Blacksmith Sparks",
    "description": "Safe watching taught respect for hot metal work.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "blacksmithing",
    "illustration": {
      "kind": "emoji",
      "emoji": "🔨",
      "alt": "Blacksmith Sparks story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Safe watching taught respect for hot metal work.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-17-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 991,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-17-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1320,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-17-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 24229,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-17-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 25657,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-18",
    "title": "Farm Morning",
    "description": "A family planted maize and sang while working.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "farming and fishing",
    "illustration": {
      "kind": "emoji",
      "emoji": "🌾",
      "alt": "Farm Morning story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "A family planted maize and sang while working.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-18-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1096,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-18-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1176,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-18-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 23385,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-18-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 24456,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-19",
    "title": "The Helpful Sibling",
    "description": "An older sibling taught counting with stones.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "kindness",
    "illustration": {
      "kind": "emoji",
      "emoji": "🧮",
      "alt": "The Helpful Sibling story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "An older sibling taught counting with stones.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-19-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1048,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-19-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1345,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-19-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 22063,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-19-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 22435,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "story-p2-20",
    "title": "Moon Over the Compound",
    "description": "Neighbours shared stories under a bright moon.",
    "contentType": "video_story",
    "discoverCategory": "african-stories",
    "levels": [
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "Stories",
    "languages": [
      "en"
    ],
    "culturalTheme": "storytelling",
    "illustration": {
      "kind": "emoji",
      "emoji": "🌕",
      "alt": "Moon Over the Compound story art"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Neighbours shared stories under a bright moon.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-20-a.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1036,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-20-b.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1060,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/story-p2-20-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 20339,
        "required": true
      }
    ],
    "game": {
      "id": "story-p2-20-q",
      "prompt": "What does this story teach?",
      "options": [
        "Kindness and good choices",
        "Being unkind",
        "Ignoring friends"
      ],
      "answer": "Kindness and good choices",
      "feedbackCorrect": "Yes — stories help us practise kindness.",
      "feedbackWrong": "Listen again for the kind choice."
    }
  }
] as LearningMediaItem[];
