/**
 * Auto-generated by scripts/gigalearn-phase2-generate.mjs — edit the script, not this file.
 * HQ posters wired by Ghana KG2 visual expansion (fal.ai).
 */
import type { LearningMediaItem } from "@/lib/gigalearn/mediaLibrary/types";

export const GHANA_PHASE2_PICTURES: LearningMediaItem[] = [
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 53454,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-1",
    "title": "Orange",
    "description": "See orange, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "fruits",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🍊",
      "alt": "Orange picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Orange",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Orange",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/orange.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 47614,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 954,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-1-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4886,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-1-g",
      "prompt": "Which one is an orange?",
      "options": [
        "🍊 Orange",
        "🍌 Banana",
        "🍆 Garden egg"
      ],
      "answer": "🍊 Orange",
      "feedbackCorrect": "Yes! That is orange.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/orange.webp",
      "alt": "A whole ripe orange with a small green leaf on a light wooden table",
      "mimeType": "image/webp",
      "estimatedBytes": 47614,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 219710,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-2",
    "title": "Coconut",
    "description": "See coconut, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "fruits",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🥥",
      "alt": "Coconut picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Coconut",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Coconut",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/coconut.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 211346,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1053,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-2-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 7311,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-2-g",
      "prompt": "Find the coconut.",
      "options": [
        "🥥 Coconut",
        "🍎 Apple",
        "🍇 Grapes"
      ],
      "answer": "🥥 Coconut",
      "feedbackCorrect": "Yes! That is coconut.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/coconut.webp",
      "alt": "A whole brown coconut and one half showing white flesh on a woven mat",
      "mimeType": "image/webp",
      "estimatedBytes": 211346,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 195225,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-3",
    "title": "Goat",
    "description": "See goat, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "animals-nature",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "animals",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🐐",
      "alt": "Goat picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Goat",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Goat",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/goat.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 189672,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1186,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-3-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4367,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-3-g",
      "prompt": "Which animal is a goat?",
      "options": [
        "🐐 Goat",
        "🐈 Cat",
        "🐓 Hen"
      ],
      "answer": "🐐 Goat",
      "feedbackCorrect": "Yes! That is goat.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/goat.webp",
      "alt": "A brown and white goat standing in a grassy West African farmyard",
      "mimeType": "image/webp",
      "estimatedBytes": 189672,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 155683,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-4",
    "title": "Hen",
    "description": "See hen, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "animals-nature",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "animals",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🐔",
      "alt": "Hen picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Hen",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Hen",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/hen.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 150330,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-4.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1145,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-4-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4208,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-4-g",
      "prompt": "Find the hen.",
      "options": [
        "🐔 Hen",
        "🐕 Dog",
        "🐄 Cow"
      ],
      "answer": "🐔 Hen",
      "feedbackCorrect": "Yes! That is hen.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/hen.webp",
      "alt": "A brown hen standing on packed earth outdoors",
      "mimeType": "image/webp",
      "estimatedBytes": 150330,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 28051,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-5",
    "title": "Red",
    "description": "See red, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "colours",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🟥",
      "alt": "Red picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Red",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Red",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/red-tomato.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 23344,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-5.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 812,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-5-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 3895,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-5-g",
      "prompt": "Which colour is red?",
      "options": [
        "🟥 Red",
        "🟦 Blue",
        "🟩 Green"
      ],
      "answer": "🟥 Red",
      "feedbackCorrect": "Yes! That is red.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/red-tomato.webp",
      "alt": "A bright red ripe tomato on a white plate",
      "mimeType": "image/webp",
      "estimatedBytes": 23344,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 57993,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-6",
    "title": "Blue",
    "description": "See blue, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "colours",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🟦",
      "alt": "Blue picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Blue",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Blue",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/blue-bowl.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 52892,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-6.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 814,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-6-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4287,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-6-g",
      "prompt": "Pick blue.",
      "options": [
        "🟦 Blue",
        "🟨 Yellow",
        "🟧 Orange"
      ],
      "answer": "🟦 Blue",
      "feedbackCorrect": "Yes! That is blue.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/blue-bowl.webp",
      "alt": "A simple bright blue plastic bowl on a light table",
      "mimeType": "image/webp",
      "estimatedBytes": 52892,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 62639,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-7",
    "title": "Three",
    "description": "See three, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "numbers-letters",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Numeracy",
    "topic": "numbers",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "3️⃣",
      "alt": "Three picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Three",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Three",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/three-oranges.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 57400,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-7.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 975,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-7-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4264,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-7-g",
      "prompt": "How many stones? 🪨🪨🪨",
      "options": [
        "2",
        "3",
        "4"
      ],
      "answer": "3",
      "feedbackCorrect": "Yes! That is three.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/three-oranges.webp",
      "alt": "Exactly three oranges arranged in a clear row for counting",
      "mimeType": "image/webp",
      "estimatedBytes": 57400,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 198568,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-8",
    "title": "Five",
    "description": "See five, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "numbers-letters",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Numeracy",
    "topic": "numbers",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "5️⃣",
      "alt": "Five picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Five",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Five",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/five-mangoes.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 192456,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-8.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1018,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-8-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5094,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-8-g",
      "prompt": "Count to five.",
      "options": [
        "4",
        "5",
        "6"
      ],
      "answer": "5",
      "feedbackCorrect": "Yes! That is five.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/five-mangoes.webp",
      "alt": "Exactly five mangoes arranged clearly for counting",
      "mimeType": "image/webp",
      "estimatedBytes": 192456,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 47851,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-9",
    "title": "Letter A",
    "description": "See letter a, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "numbers-letters",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "letters",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🅰️",
      "alt": "Letter A picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Letter A",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Letter A",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/letter-a-apple.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 41002,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-9.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1003,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-9-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5846,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-9-g",
      "prompt": "Which letter is A?",
      "options": [
        "A",
        "B",
        "C"
      ],
      "answer": "A",
      "feedbackCorrect": "Yes! That is letter a.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/letter-a-apple.webp",
      "alt": "A shiny red apple with a green leaf for letter A phonics",
      "mimeType": "image/webp",
      "estimatedBytes": 41002,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 94619,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-10",
    "title": "Letter B",
    "description": "See letter b, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "numbers-letters",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Language",
    "topic": "letters",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🅱️",
      "alt": "Letter B picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Letter B",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Letter B",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/letter-b-ball.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 87600,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-10.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 834,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-10-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 6185,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-10-g",
      "prompt": "Find B.",
      "options": [
        "A",
        "B",
        "D"
      ],
      "answer": "B",
      "feedbackCorrect": "Yes! That is letter b.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/letter-b-ball.webp",
      "alt": "A black and white football (soccer ball) on grass",
      "mimeType": "image/webp",
      "estimatedBytes": 87600,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 91274,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-11",
    "title": "Circle",
    "description": "See circle, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "shapes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "⭕",
      "alt": "Circle picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Circle",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Circle",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/circle-plate.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 84514,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-11.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 832,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-11-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5928,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-11-g",
      "prompt": "Which shape is a circle?",
      "options": [
        "⭕ Circle",
        "⬛ Square",
        "🔺 Triangle"
      ],
      "answer": "⭕ Circle",
      "feedbackCorrect": "Yes! That is circle.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/circle-plate.webp",
      "alt": "A round white plate showing a clear circle shape",
      "mimeType": "image/webp",
      "estimatedBytes": 84514,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 33215,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-12",
    "title": "Square",
    "description": "See square, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "shapes",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "⬛",
      "alt": "Square picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Square",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Square",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/square-tile.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 26394,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-12.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 866,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-12-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5955,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-12-g",
      "prompt": "Find the square.",
      "options": [
        "⬛ Square",
        "⭕ Circle",
        "⭐ Star"
      ],
      "answer": "⬛ Square",
      "feedbackCorrect": "Yes! That is square.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/square-tile.webp",
      "alt": "A square wooden tile or block showing equal sides",
      "mimeType": "image/webp",
      "estimatedBytes": 26394,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 35502,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-13",
    "title": "Hand",
    "description": "See hand, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "body",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "✋",
      "alt": "Hand picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Hand",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Hand",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/hand.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 30110,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-13.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1132,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-13-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4260,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-13-g",
      "prompt": "Which is a hand?",
      "options": [
        "✋ Hand",
        "👂 Ear",
        "👃 Nose"
      ],
      "answer": "✋ Hand",
      "feedbackCorrect": "Yes! That is hand.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/hand.webp",
      "alt": "A child's open hand palm facing camera on a soft background",
      "mimeType": "image/webp",
      "estimatedBytes": 30110,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 144514,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-14",
    "title": "Eye",
    "description": "See eye, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "body",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👁️",
      "alt": "Eye picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Eye",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Eye",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/eye.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 140020,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-14.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 885,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-14-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 3609,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-14-g",
      "prompt": "Find the eye.",
      "options": [
        "👁️ Eye",
        "🦷 Tooth",
        "🦵 Leg"
      ],
      "answer": "👁️ Eye",
      "feedbackCorrect": "Yes! That is eye.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/eye.webp",
      "alt": "A close-up of a child's eye with clear iris, educational and respectful",
      "mimeType": "image/webp",
      "estimatedBytes": 140020,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 21641,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-15",
    "title": "Cup",
    "description": "See cup, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "household",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "☕",
      "alt": "Cup picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Cup",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Cup",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/cup.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 17132,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-15.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 924,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-15-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 3585,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-15-g",
      "prompt": "Which is a cup?",
      "options": [
        "☕ Cup",
        "🪑 Chair",
        "🛏️ Bed"
      ],
      "answer": "☕ Cup",
      "feedbackCorrect": "Yes! That is cup.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/cup.webp",
      "alt": "A simple ceramic cup on a wooden table",
      "mimeType": "image/webp",
      "estimatedBytes": 17132,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 52824,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-16",
    "title": "Chair",
    "description": "See chair, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "household",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🪑",
      "alt": "Chair picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Chair",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Chair",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/chair.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 47334,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-16.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1073,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-16-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4417,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-16-g",
      "prompt": "Find the chair.",
      "options": [
        "🪑 Chair",
        "🚪 Door",
        "🪟 Window"
      ],
      "answer": "🪑 Chair",
      "feedbackCorrect": "Yes! That is chair.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/chair.webp",
      "alt": "A simple wooden chair in a bright classroom corner",
      "mimeType": "image/webp",
      "estimatedBytes": 47334,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 106201,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-17",
    "title": "Teacher",
    "description": "See teacher, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "occupations",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👩‍🏫",
      "alt": "Teacher picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Teacher",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Teacher",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/teacher.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 100024,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-17.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 951,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-17-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5226,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-17-g",
      "prompt": "Who helps us learn at school?",
      "options": [
        "Teacher",
        "Pilot",
        "Chef"
      ],
      "answer": "Teacher",
      "feedbackCorrect": "Yes! That is teacher.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/teacher.webp",
      "alt": "A smiling Ghanaian woman teacher beside a chalkboard in a classroom",
      "mimeType": "image/webp",
      "estimatedBytes": 100024,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 158089,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-18",
    "title": "Farmer",
    "description": "See farmer, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "pictures-objects",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "occupations",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👩‍🌾",
      "alt": "Farmer picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Farmer",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Farmer",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/farmer.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 151884,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-18.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1008,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-18-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 5197,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-18-g",
      "prompt": "Who grows food on the farm?",
      "options": [
        "Farmer",
        "Driver",
        "Nurse"
      ],
      "answer": "Farmer",
      "feedbackCorrect": "Yes! That is farmer.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/farmer.webp",
      "alt": "A Ghanaian farmer with a hoe in a green field",
      "mimeType": "image/webp",
      "estimatedBytes": 151884,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 89660,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-19",
    "title": "River",
    "description": "See river, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "animals-nature",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "environment",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🏞️",
      "alt": "River picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "River",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "River",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/river.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 84048,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-19.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 989,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-19-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 4623,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-19-g",
      "prompt": "Where does a fish live?",
      "options": [
        "River",
        "Cupboard",
        "Book"
      ],
      "answer": "River",
      "feedbackCorrect": "Yes! That is river.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/river.webp",
      "alt": "A calm river with green banks under soft daylight",
      "mimeType": "image/webp",
      "estimatedBytes": 84048,
      "aspectRatio": "1:1"
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 135042,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.; Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "pic-p2-20",
    "title": "Tree",
    "description": "See tree, hear the name, then play a short identification game.",
    "contentType": "picture_card",
    "discoverCategory": "animals-nature",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "environment",
    "languages": [
      "en",
      "tw"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "🌳",
      "alt": "Tree picture"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Tree",
        "voiceId": "english",
        "language": "en"
      },
      {
        "kind": "tts",
        "text": "Tree",
        "voiceId": "abena-twi",
        "language": "tw"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/tree.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 130144,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-20.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1001,
        "required": false
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/pic-p2-20-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 3897,
        "required": true
      }
    ],
    "game": {
      "id": "pic-p2-20-g",
      "prompt": "What gives us shade and fruit?",
      "options": [
        "Tree",
        "Shoe",
        "Phone"
      ],
      "answer": "Tree",
      "feedbackCorrect": "Yes! That is tree.",
      "feedbackWrong": "Look again carefully."
    },
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/tree.webp",
      "alt": "A large shade tree with green leaves in a Ghanaian landscape",
      "mimeType": "image/webp",
      "estimatedBytes": 130144,
      "aspectRatio": "1:1"
    }
  }
];
