/**
 * Auto-generated by scripts/gigalearn-phase2-generate.mjs — edit the script, not this file.
 */
import type { LearningMediaItem } from "@/lib/gigalearn/mediaLibrary/types";

export const GHANA_PHASE2_SONGS: LearningMediaItem[] = [
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 36714,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-1",
    "title": "Clap and Count",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Clap one, clap two, clap three with me — counting is fun, you will see!",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Clap and Count chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Clap one, clap two, clap three with me — counting is fun, you will see!",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-1.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1339,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-1-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 35375,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-1-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 29352,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-2",
    "title": "Hello Friend",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Hello friend, how do you do? I am glad to learn with you.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Hello Friend chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Hello friend, how do you do? I am glad to learn with you.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-2.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1051,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-2-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 28301,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-2-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 32153,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-3",
    "title": "Wash Your Hands",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Wash your hands, wash your hands, soap and water, clean again.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Wash Your Hands chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Wash your hands, wash your hands, soap and water, clean again.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-3.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 992,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-3-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31161,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-3-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 31564,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-4",
    "title": "Colours Everywhere",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Red and yellow, green and blue — colours shine for me and you.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Colours Everywhere chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Red and yellow, green and blue — colours shine for me and you.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-4.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1049,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-4-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 30515,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-4-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 31224,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-5",
    "title": "Walk to School",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Left and right, step by step, walking to school with pep.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Walk to School chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Left and right, step by step, walking to school with pep.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-5.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 980,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-5-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 30244,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-5-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 34004,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-6",
    "title": "Thank You Chant",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Thank you Mama, thank you teacher — gratitude makes kindness richer.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Thank You Chant chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Thank you Mama, thank you teacher — gratitude makes kindness richer.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-6.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 853,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-6-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 33151,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-6-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 27773,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-7",
    "title": "River Fish",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Little fish in the river bright, swim along from morning light.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "River Fish chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Little fish in the river bright, swim along from morning light.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-7.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 956,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-7-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 26817,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-7-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 29768,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-8",
    "title": "Farmers Dig",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Dig dig dig, plant plant plant — farmers feed our land.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Farmers Dig chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Dig dig dig, plant plant plant — farmers feed our land.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-8.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1094,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-8-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 28674,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-8-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 37182,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-9",
    "title": "Good Morning Ghana",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Good morning Ghana, skies so blue, we learn and play the whole day through.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Good Morning Ghana chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Good morning Ghana, skies so blue, we learn and play the whole day through.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-9.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1178,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-9-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 36004,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-9-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 30246,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-10",
    "title": "Share the Ball",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Pass the ball, do not grab — sharing makes a happy class.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Share the Ball chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Pass the ball, do not grab — sharing makes a happy class.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-10.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1314,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-10-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 28932,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-10-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 28618,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-11",
    "title": "Alphabet Bounce",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): A B C, bounce with me — letters dance so playfully.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Alphabet Bounce chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "A B C, bounce with me — letters dance so playfully.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-11.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1017,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-11-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 27601,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-11-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 36899,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-12",
    "title": "Quiet Time",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Soft as cotton, calm and slow — quiet time helps good minds grow.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Quiet Time chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Soft as cotton, calm and slow — quiet time helps good minds grow.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-12.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1012,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-12-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 35887,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-12-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 33881,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-13",
    "title": "Market Call",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Come buy oranges, come buy yam — market calls are Ghana's jam.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Market Call chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Come buy oranges, come buy yam — market calls are Ghana's jam.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-13.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1226,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-13-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 32655,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-13-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 33024,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-14",
    "title": "Brave Little Ant",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Ant so small but works so hard — courage lives in every yard.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Brave Little Ant chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Ant so small but works so hard — courage lives in every yard.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-14.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1259,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-14-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 31765,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-14-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  },
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 30510,
    "offlineEligible": true,
    "rights": {
      "source": "English audio generated with espeak-ng en+m3 (warmer male spoken narration). Local-language labels use browser TTS female profiles (Abena/Naa) unchanged. Spoken TTS — not a melodic music recording; not educator-reviewed native speech.",
      "rights": "original",
      "reviewed": false
    },
    "id": "song-p2-15",
    "title": "Evening Thanks",
    "description": "Spoken lyric chant for early years (TTS word rhythm to clap or say along — not a melodic music recording): Day is done, stars appear — thank you for the friends so dear.",
    "contentType": "rhyme_song",
    "discoverCategory": "songs",
    "levels": [
      "KG1",
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Creative Arts",
    "topic": "Spoken lyric chants",
    "languages": [
      "en"
    ],
    "illustration": {
      "kind": "emoji",
      "emoji": "👏",
      "alt": "Evening Thanks chant illustration"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "Day is done, stars appear — thank you for the friends so dear.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-15.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1054,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/song-p2-15-en.mp3",
        "mimeType": "audio/mpeg",
        "estimatedBytes": 29456,
        "required": true
      }
    ],
    "game": {
      "id": "song-p2-15-q",
      "prompt": "What should we do with a spoken chant?",
      "options": [
        "Listen and say the words together",
        "Shout over friends",
        "Hide the words"
      ],
      "answer": "Listen and say the words together",
      "feedbackCorrect": "Yes — listen and say the words kindly.",
      "feedbackWrong": "Try again — chants work best when we listen."
    }
  }
] as LearningMediaItem[];
