/**
 * Auto-generated by scripts/gigalearn-phase2-generate.mjs — edit the script, not this file.
 * HQ posters wired by Ghana KG2 visual expansion (fal.ai).
 */
import type { LearningMediaItem } from "@/lib/gigalearn/mediaLibrary/types";

export const GHANA_PHASE2_CULTURE: LearningMediaItem[] = [
  {
    "countryId": "ghana",
    "countryCode": "GH",
    "regionScope": "country",
    "curriculumId": "gh-ccp",
    "curriculumLevelId": "basic-1",
    "curriculumNote": "Ghana Early Years / lower primary oral language",
    "ageSuitability": {
      "minAge": 5,
      "maxAge": 8,
      "label": "KG2–P2 (ages 5–8)"
    },
    "estimatedOfflineBytes": 120438,
    "offlineEligible": true,
    "rights": {
      "source": "Original Giga3 educational content for Ghana early years (Phase 2); Original Giga3 AI-generated photographic asset (fal.ai) — educator visual review pending",
      "rights": "original",
      "reviewed": false
    },
    "id": "culture-p2-potter",
    "title": "Village Potter",
    "description": "Potters shape clay into bowls used at home and in markets across Ghana.",
    "contentType": "culture",
    "discoverCategory": "culture-occupations",
    "levels": [
      "KG2",
      "P1",
      "P2"
    ],
    "subject": "Our World",
    "topic": "Occupations",
    "languages": [
      "en"
    ],
    "culturalTheme": "pottery",
    "illustration": {
      "kind": "emoji",
      "emoji": "🏺",
      "alt": "Potter at work"
    },
    "narrations": [
      {
        "kind": "tts",
        "text": "A potter shapes soft clay into a useful pot.",
        "voiceId": "english",
        "language": "en"
      }
    ],
    "remoteMedia": [
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/kg2/hq/potter.webp",
        "mimeType": "image/webp",
        "estimatedBytes": 119418,
        "required": true
      },
      {
        "kind": "remote",
        "url": "/gigalearn/media/ghana/phase2/culture-p2-potter.svg",
        "mimeType": "image/svg+xml",
        "estimatedBytes": 1020,
        "required": false
      }
    ],
    "posterImage": {
      "url": "/gigalearn/media/ghana/kg2/hq/potter.webp",
      "alt": "A Ghanaian potter shaping a clay pot on a workshop floor",
      "mimeType": "image/webp",
      "estimatedBytes": 119418,
      "aspectRatio": "1:1"
    }
  }
];
