import type { GigaRhyme, RhymeCategory, RhymeCategoryId } from "@/lib/gigalearn/rhymes/types";

/**
 * GigaRhymes launch library — every rhyme below was written for Giga3.
 * No lyrics, titles, melodies or line structures were taken from existing
 * songs, nursery rhymes or social-media videos.
 */

export const RHYME_CATEGORIES: RhymeCategory[] = [
  { id: "alphabet", label: "Alphabet", emoji: "🔤", description: "Letters with everyday African things" },
  { id: "numbers", label: "Numbers & Counting", emoji: "🔢", description: "Count, add and compare" },
  { id: "fruits-vegetables", label: "Fruits & Vegetables", emoji: "🥭", description: "Healthy food from farm and market" },
  { id: "african-animals", label: "African Animals", emoji: "🦒", description: "Wildlife and where it lives" },
  { id: "colours", label: "Colours", emoji: "🎨", description: "Name and spot colours around us" },
  { id: "health-hygiene", label: "Health & Hygiene", emoji: "🧼", description: "Clean hands, teeth and habits" },
  { id: "good-manners", label: "Good Manners", emoji: "🤝", description: "Respect, kindness and greetings" },
  { id: "school", label: "School", emoji: "🏫", description: "Routines and school life" },
  { id: "nature-environment", label: "Nature & Environment", emoji: "🌳", description: "Care for plants, water and streets" },
  { id: "movement-actions", label: "Movement & Actions", emoji: "🤸", description: "Move, stretch and play" },
  { id: "african-languages", label: "African Languages", emoji: "🗣️", description: "Simple words in African languages" },
  { id: "ghana-african-culture", label: "Ghana & African Culture", emoji: "🥁", description: "Festivals, crafts and traditions" },
];

const TTS = { kind: "tts", voiceId: "english" } as const;
const ORIGINAL = { sourceType: "original", originalContent: true, reviewed: false } as const;

export const GIGA_RHYMES: GigaRhyme[] = [
  {
    id: "letters-at-the-market",
    title: "Letters at the Market",
    category: "alphabet",
    ageRange: "3–5 years",
    learningObjective: "Match the letters A, B, C and D to their first sounds.",
    description: "Four market and farm foods introduce the first four letters.",
    lyrics: [
      "A for avocado, green and round,",
      "B for beans that grow in the ground,",
      "C for cassava — dig, dig, dig!",
      "D for the drum that goes boom, big!",
    ],
    language: "English",
    region: "West Africa",
    culturalContext: "Foods sold in West African markets",
    difficulty: "easy",
    keywords: ["letters", "phonics", "market", "food"],
    illustration: { emoji: "🥑", alt: "An avocado" },
    audio: TTS,
    activities: [
      "Draw the letter A in the air, then draw an avocado.",
      "Find something in the classroom that starts with B, C or D.",
    ],
    questions: [
      { id: "q1", prompt: "Which food starts with C?", options: ["Cassava", "Beans", "Avocado"], answer: "Cassava" },
      { id: "q2", prompt: "What goes boom?", options: ["The drum", "The beans", "The avocado"], answer: "The drum" },
    ],
    ...ORIGINAL,
  },
  {
    id: "e-to-h-on-the-farm",
    title: "E to H on the Farm",
    category: "alphabet",
    ageRange: "4–6 years",
    learningObjective: "Say the letters E, F, G and H and a word for each.",
    description: "A walk around a small farm meets four new letters.",
    lyrics: [
      "E for the egg our hen has laid,",
      "F for the farmer resting in the shade,",
      "G for the goat who loves to play,",
      "H for the hoe we use each day.",
    ],
    language: "English",
    region: "West Africa",
    culturalContext: "Family farm life",
    difficulty: "easy",
    keywords: ["letters", "farm", "animals"],
    illustration: { emoji: "🐐", alt: "A goat" },
    audio: TTS,
    activities: [
      "Act out each line: lay an egg, rest in the shade, play like a goat, dig with a hoe.",
      "Write E, F, G and H and draw a picture beside each letter.",
    ],
    questions: [
      { id: "q1", prompt: "Which letter is for goat?", options: ["G", "H", "E"], answer: "G" },
      { id: "q2", prompt: "What does the farmer use each day?", options: ["A hoe", "An egg", "A goat"], answer: "A hoe" },
    ],
    ...ORIGINAL,
  },
  {
    id: "kofis-groundnut-basket",
    title: "Kofi's Groundnut Basket",
    category: "numbers",
    ageRange: "4–6 years",
    learningObjective: "Count objects to 3, then add 2 more to make 5.",
    description: "Kofi counts groundnuts and discovers that 3 and 2 make 5.",
    lyrics: [
      "Kofi has a basket, let us look inside:",
      "Groundnuts for the counting, sitting side by side.",
      "Point and count them slowly — one, two, three,",
      "Add two more to make it five — count along with me!",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Groundnuts as a common Ghanaian snack",
    difficulty: "easy",
    keywords: ["counting", "addition", "groundnuts"],
    illustration: { emoji: "🥜", alt: "Groundnuts" },
    audio: TTS,
    activities: [
      "Use five stones or bottle tops: count three, then add two more.",
      "Show five fingers and count them one by one.",
    ],
    questions: [
      { id: "q1", prompt: "Kofi counts three groundnuts and adds two. How many now?", options: ["4", "5", "6"], answer: "5" },
      { id: "q2", prompt: "Where are the groundnuts?", options: ["In a basket", "In a bag", "On a tree"], answer: "In a basket" },
    ],
    ...ORIGINAL,
  },
  {
    id: "tro-tro-counting",
    title: "Tro-tro Counting",
    category: "numbers",
    ageRange: "4–6 years",
    learningObjective: "Count people as they are added, from 1 to 3.",
    description: "Riders board a tro-tro one by one while learners count.",
    lyrics: [
      "Beep, beep! The tro-tro stops for Ama — that is one,",
      "Kwesi hops on after her — now two have come.",
      "Grandma with her basket climbs in — that makes three,",
      "Count the riders on the tro-tro: one, two, three!",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Tro-tro minibuses used for everyday travel in Ghana",
    difficulty: "easy",
    keywords: ["counting", "transport", "tro-tro"],
    illustration: { emoji: "🚐", alt: "A minibus" },
    audio: TTS,
    activities: [
      "Line up chairs as a tro-tro and let learners 'board' while the class counts.",
      "Draw three people on a bus and number them 1, 2, 3.",
    ],
    questions: [
      { id: "q1", prompt: "Who got on first?", options: ["Ama", "Kwesi", "Grandma"], answer: "Ama" },
      { id: "q2", prompt: "How many riders are there at the end?", options: ["2", "3", "4"], answer: "3" },
    ],
    ...ORIGINAL,
  },
  {
    id: "pawpaw-morning",
    title: "Pawpaw Morning",
    category: "fruits-vegetables",
    ageRange: "3–5 years",
    learningObjective: "Describe a pawpaw by colour, taste and seeds, and know to wash fruit.",
    description: "A breakfast rhyme about preparing and sharing pawpaw.",
    lyrics: [
      "Orange pawpaw, soft and sweet,",
      "Black seeds hiding — what a treat!",
      "Wash it, cut it, share a slice,",
      "Fruit for breakfast — oh, so nice!",
    ],
    language: "English",
    region: "West Africa",
    culturalContext: "Pawpaw (papaya) as a home-grown fruit",
    difficulty: "easy",
    keywords: ["fruit", "pawpaw", "healthy eating"],
    illustration: { emoji: "🍈", alt: "A pawpaw" },
    audio: TTS,
    activities: [
      "Mime washing, cutting and sharing a pawpaw.",
      "Name two other fruits you can eat for breakfast.",
    ],
    questions: [
      { id: "q1", prompt: "What colour are pawpaw seeds?", options: ["Black", "White", "Green"], answer: "Black" },
      { id: "q2", prompt: "What do we do before cutting fruit?", options: ["Wash it", "Throw it", "Hide it"], answer: "Wash it" },
    ],
    ...ORIGINAL,
  },
  {
    id: "into-mamas-pot",
    title: "Into Mama's Pot",
    category: "fruits-vegetables",
    ageRange: "4–6 years",
    learningObjective: "Name four vegetables and their colours.",
    description: "Vegetables from the garden go into a family stew.",
    lyrics: [
      "Garden egg is round and white,",
      "Kontomire leaves are green and bright,",
      "Tomato red and pepper hot,",
      "All go into Mama's pot!",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Ghanaian home cooking — kontomire (cocoyam leaf) stew",
    difficulty: "easy",
    keywords: ["vegetables", "colours", "cooking"],
    illustration: { emoji: "🍅", alt: "A tomato" },
    audio: TTS,
    activities: [
      "Sort pictures of vegetables into colour groups.",
      "Tell a partner which vegetable you like best and why.",
    ],
    questions: [
      { id: "q1", prompt: "What colour are kontomire leaves?", options: ["Green", "Red", "White"], answer: "Green" },
      { id: "q2", prompt: "Which vegetable is hot?", options: ["Pepper", "Garden egg", "Tomato"], answer: "Pepper" },
    ],
    ...ORIGINAL,
  },
  {
    id: "savannah-friends",
    title: "Savannah Friends",
    category: "african-animals",
    ageRange: "4–6 years",
    learningObjective: "Name four savannah animals and one feature of each.",
    description: "Learners meet a giraffe, zebra, elephant and lion.",
    lyrics: [
      "Giraffe stretches up to the treetops high,",
      "Zebra's stripes go dashing by,",
      "Elephant splashes — splish and splash!",
      "Lion wakes up in a flash!",
    ],
    language: "English",
    region: "Across Africa",
    culturalContext: "Savannah wildlife, e.g. Mole National Park (Ghana) or the Serengeti (Tanzania)",
    difficulty: "easy",
    keywords: ["animals", "savannah", "wildlife"],
    illustration: { emoji: "🦒", alt: "A giraffe" },
    audio: TTS,
    activities: [
      "Move like each animal: stretch tall, dash, splash, pounce.",
      "Draw your favourite savannah animal and label one body part.",
    ],
    questions: [
      { id: "q1", prompt: "Which animal has stripes?", options: ["Zebra", "Lion", "Giraffe"], answer: "Zebra" },
      { id: "q2", prompt: "Which animal reaches the treetops?", options: ["Giraffe", "Elephant", "Zebra"], answer: "Giraffe" },
    ],
    ...ORIGINAL,
  },
  {
    id: "paga-crocodile",
    title: "The Crocodile of Paga",
    category: "african-animals",
    ageRange: "5–7 years",
    learningObjective: "Describe a crocodile's body and where it lives.",
    description: "A visit to the crocodile ponds of Paga in northern Ghana.",
    lyrics: [
      "Down by the pond in Paga town,",
      "A crocodile is lying down.",
      "Bumpy back and a long, strong tail,",
      "Four short legs and teeth like nails!",
    ],
    language: "English",
    region: "Upper East Region, Ghana",
    culturalContext: "The Paga crocodile ponds (Kasena community)",
    difficulty: "medium",
    keywords: ["animals", "reptiles", "habitat"],
    illustration: { emoji: "🐊", alt: "A crocodile" },
    audio: TTS,
    activities: [
      "Count the legs of a crocodile, a hen and a goat. Who has the most?",
      "Talk about why we watch wild animals from a safe distance.",
    ],
    questions: [
      { id: "q1", prompt: "Where does the crocodile live?", options: ["In a pond", "In a tree", "In a house"], answer: "In a pond" },
      { id: "q2", prompt: "How many legs does a crocodile have?", options: ["Four", "Two", "Six"], answer: "Four" },
    ],
    ...ORIGINAL,
  },
  {
    id: "colours-of-kente",
    title: "Colours of the Kente",
    category: "colours",
    ageRange: "4–6 years",
    learningObjective: "Name yellow, green, red and blue and link each to something real.",
    description: "Colours in a kente cloth are matched to things around us.",
    lyrics: [
      "Yellow like the morning sun,",
      "Green like leaves when rain has come,",
      "Red like pepper in the stew,",
      "Blue like the sky — in kente too!",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Kente weaving traditions of the Asante and Ewe peoples",
    difficulty: "easy",
    keywords: ["colours", "kente", "weaving"],
    illustration: { emoji: "🧵", alt: "A spool of thread" },
    audio: TTS,
    activities: [
      "Weave strips of coloured paper into a simple pattern.",
      "Find something yellow, green, red and blue in the room.",
    ],
    questions: [
      { id: "q1", prompt: "What is yellow like the morning sun?", options: ["Yellow", "Blue", "Green"], answer: "Yellow" },
      { id: "q2", prompt: "Which colour is the pepper?", options: ["Red", "Blue", "Yellow"], answer: "Red" },
    ],
    ...ORIGINAL,
  },
  {
    id: "market-rainbow",
    title: "Market Rainbow",
    category: "colours",
    ageRange: "5–7 years",
    learningObjective: "Name six colours using foods found at a market.",
    description: "A market seller's tray becomes a rainbow of colours.",
    lyrics: [
      "Orange carrots, purple onions piled up high,",
      "Yellow maize and green okra — come and buy!",
      "White rice, brown beans in the seller's tray,",
      "How many colours can you name today?",
    ],
    language: "English",
    region: "West Africa",
    culturalContext: "An open-air community market",
    difficulty: "medium",
    keywords: ["colours", "market", "food"],
    illustration: { emoji: "🌽", alt: "An ear of maize" },
    audio: TTS,
    activities: [
      "Play 'market seller': one learner names a colour, others point to a matching food picture.",
      "Count how many colours are in the rhyme.",
    ],
    questions: [
      { id: "q1", prompt: "What colour is the okra?", options: ["Green", "Purple", "White"], answer: "Green" },
      { id: "q2", prompt: "Which food is brown?", options: ["Beans", "Rice", "Maize"], answer: "Beans" },
    ],
    ...ORIGINAL,
  },
  {
    id: "veronica-bucket",
    title: "At the Veronica Bucket",
    category: "health-hygiene",
    ageRange: "4–6 years",
    learningObjective: "Follow the steps for washing hands with soap for 20 seconds.",
    description: "Handwashing steps at a Veronica bucket with a tap.",
    lyrics: [
      "Open the tap on the Veronica pail,",
      "Wet my hands from wrist to nail,",
      "Soap and scrub while I count to twenty,",
      "Rinse them clean — germs? Not any!",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Veronica buckets (water buckets with a tap) used for handwashing in Ghanaian schools",
    difficulty: "easy",
    keywords: ["handwashing", "hygiene", "health"],
    illustration: { emoji: "🧼", alt: "A bar of soap" },
    audio: TTS,
    activities: [
      "Practise the four steps at a real bucket or basin.",
      "Count slowly to twenty together while miming scrubbing.",
    ],
    questions: [
      { id: "q1", prompt: "How long do we scrub with soap?", options: ["Count to twenty", "Count to two", "No time"], answer: "Count to twenty" },
      { id: "q2", prompt: "What do we do last?", options: ["Rinse", "Wet", "Open the tap"], answer: "Rinse" },
    ],
    ...ORIGINAL,
  },
  {
    id: "shiny-smile",
    title: "A Shiny Smile",
    category: "health-hygiene",
    ageRange: "3–5 years",
    learningObjective: "Know to brush all teeth in the morning and before sleeping.",
    description: "A toothbrushing routine for morning and night.",
    lyrics: [
      "Up and down and round I go,",
      "Top teeth, bottom teeth, row by row,",
      "When I wake and before I sleep,",
      "A shiny smile is mine to keep!",
    ],
    language: "English",
    region: "Everywhere",
    culturalContext: "Daily home routine",
    difficulty: "easy",
    keywords: ["teeth", "hygiene", "routine"],
    illustration: { emoji: "🪥", alt: "A toothbrush" },
    audio: TTS,
    activities: [
      "Mime brushing: up and down, then in small circles.",
      "Draw a clock showing when you brush your teeth.",
    ],
    questions: [
      { id: "q1", prompt: "When do we brush our teeth?", options: ["Morning and night", "Only on Sunday", "Never"], answer: "Morning and night" },
      { id: "q2", prompt: "Which teeth do we brush?", options: ["Top and bottom", "Only the top", "Only one tooth"], answer: "Top and bottom" },
    ],
    ...ORIGINAL,
  },
  {
    id: "greeting-grandpa",
    title: "When Grandpa Comes",
    category: "good-manners",
    ageRange: "5–7 years",
    learningObjective: "Show respect to elders by greeting them and using the right hand.",
    description: "How a child welcomes an elder at home.",
    lyrics: [
      "When Grandpa comes, I stand up tall,",
      "I greet him first — 'Good morning!' to all.",
      "I give and receive with my right hand,",
      "Respect is how good families stand.",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Ghanaian home etiquette: greeting elders first and giving with the right hand",
    difficulty: "easy",
    keywords: ["respect", "elders", "greetings"],
    illustration: { emoji: "👴🏾", alt: "A grandfather" },
    audio: TTS,
    activities: [
      "Role-play greeting an elder who visits the classroom.",
      "Practise passing a book to a partner with the right hand.",
    ],
    questions: [
      { id: "q1", prompt: "Which hand do we use to give things?", options: ["Right hand", "Left hand", "No hand"], answer: "Right hand" },
      { id: "q2", prompt: "What do we do when Grandpa comes?", options: ["Stand and greet him", "Hide", "Keep sitting"], answer: "Stand and greet him" },
    ],
    ...ORIGINAL,
  },
  {
    id: "kind-little-words",
    title: "Kind Little Words",
    category: "good-manners",
    ageRange: "4–6 years",
    learningObjective: "Use 'please', 'thank you' and 'sorry' in the right situations.",
    description: "Three friends practise polite words while playing.",
    lyrics: [
      "When I want the ball, I ask, 'May I, please?'",
      "When Esi shares her mango, 'Thank you!' comes with ease.",
      "If I bump into Yaw, I say, 'Sorry, my friend,'",
      "Kind little words help friendships mend.",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Children playing together at school",
    difficulty: "easy",
    keywords: ["manners", "kindness", "friendship"],
    illustration: { emoji: "🤝", alt: "Two hands shaking" },
    audio: TTS,
    activities: [
      "Act out each situation in pairs.",
      "Make a 'kind words' poster for the classroom.",
    ],
    questions: [
      { id: "q1", prompt: "What do we say when someone shares?", options: ["Thank you", "Go away", "Mine"], answer: "Thank you" },
      { id: "q2", prompt: "What do we say after bumping into someone?", options: ["Sorry", "Please", "Hello"], answer: "Sorry" },
    ],
    ...ORIGINAL,
  },
  {
    id: "morning-assembly",
    title: "Morning Assembly",
    category: "school",
    ageRange: "5–7 years",
    learningObjective: "Describe the order of the morning school routine.",
    description: "Lining up, singing and walking calmly to class.",
    lyrics: [
      "The bell rings out across the yard,",
      "We line up straight — it isn't hard!",
      "We sing our song and stand up proud,",
      "Then walk to class — but not too loud!",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Morning assembly in a Ghanaian basic school",
    difficulty: "easy",
    keywords: ["school", "routine", "sequence"],
    illustration: { emoji: "🔔", alt: "A bell" },
    audio: TTS,
    activities: [
      "Put four picture cards of the routine in the right order.",
      "Practise lining up quietly in under ten seconds.",
    ],
    questions: [
      { id: "q1", prompt: "What happens first?", options: ["The bell rings", "We walk to class", "We sing"], answer: "The bell rings" },
      { id: "q2", prompt: "How do we walk to class?", options: ["Quietly", "Shouting", "Running"], answer: "Quietly" },
    ],
    ...ORIGINAL,
  },
  {
    id: "my-school-bag",
    title: "My School Bag",
    category: "school",
    ageRange: "4–6 years",
    learningObjective: "Name the items needed for school and pack them.",
    description: "A child packs a school bag for the day.",
    lyrics: [
      "In my bag I pack my book,",
      "A pencil sharp — come take a look!",
      "My ruler, eraser, water too,",
      "Ready for school — and so are you!",
    ],
    language: "English",
    region: "Everywhere",
    culturalContext: "Getting ready for school",
    difficulty: "easy",
    keywords: ["school", "objects", "preparation"],
    illustration: { emoji: "🎒", alt: "A school bag" },
    audio: TTS,
    activities: [
      "Pack a real bag with the items in the rhyme and count them.",
      "Draw your school bag and label what is inside.",
    ],
    questions: [
      { id: "q1", prompt: "What do we write with?", options: ["A pencil", "A ruler", "Water"], answer: "A pencil" },
      { id: "q2", prompt: "How many items are packed in the rhyme?", options: ["Five", "Two", "Nine"], answer: "Five" },
    ],
    ...ORIGINAL,
  },
  {
    id: "plant-a-tree",
    title: "Plant a Tree",
    category: "nature-environment",
    ageRange: "5–7 years",
    learningObjective: "State what a seed needs to grow and why trees help us.",
    description: "Planting a seed and watching it become a shady tree.",
    lyrics: [
      "Dig a hole and drop a seed,",
      "Water is the drink it needs,",
      "Sunshine helps it grow up high,",
      "Shade for us when days are dry.",
    ],
    language: "English",
    region: "West Africa",
    culturalContext: "Tree planting during the dry Harmattan season",
    difficulty: "easy",
    keywords: ["plants", "environment", "growth"],
    illustration: { emoji: "🌱", alt: "A seedling" },
    audio: TTS,
    activities: [
      "Plant a bean seed in a cup and water it every day.",
      "List three ways trees help people and animals.",
    ],
    questions: [
      { id: "q1", prompt: "What does a seed need to drink?", options: ["Water", "Soap", "Milk"], answer: "Water" },
      { id: "q2", prompt: "What does a big tree give us on dry days?", options: ["Shade", "Rain", "Snow"], answer: "Shade" },
    ],
    ...ORIGINAL,
  },
  {
    id: "sachet-in-the-bin",
    title: "Sachet in the Bin",
    category: "nature-environment",
    ageRange: "5–7 years",
    learningObjective: "Explain why rubbish goes in the bin and keeps gutters clear.",
    description: "An empty water sachet finds the right place.",
    lyrics: [
      "When my water sachet is empty and thin,",
      "I don't drop it down — it goes in the bin!",
      "Clean gutters, clean streets, clean rivers that flow,",
      "We keep our town tidy wherever we go!",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Sachet drinking water and keeping gutters clear in Ghanaian towns",
    difficulty: "easy",
    keywords: ["environment", "rubbish", "community"],
    illustration: { emoji: "🗑️", alt: "A rubbish bin" },
    audio: TTS,
    activities: [
      "Do a five-minute class litter pick and count what you collect.",
      "Talk about what happens when gutters are blocked during the rainy season.",
    ],
    questions: [
      { id: "q1", prompt: "Where does the empty sachet go?", options: ["In the bin", "On the road", "In the gutter"], answer: "In the bin" },
      { id: "q2", prompt: "What do we keep clean?", options: ["Gutters and streets", "Only our shoes", "Nothing"], answer: "Gutters and streets" },
    ],
    ...ORIGINAL,
  },
  {
    id: "palm-tree-stretch",
    title: "Palm Tree Stretch",
    category: "movement-actions",
    ageRange: "3–5 years",
    learningObjective: "Follow action words: stretch, sway, bend and wiggle.",
    description: "A warm-up that copies palm trees, farmers and rain.",
    lyrics: [
      "Stretch up high like a palm tree tall,",
      "Sway in the breeze, but do not fall,",
      "Bend down low like a farmer sowing,",
      "Wiggle your fingers like raindrops flowing!",
    ],
    language: "English",
    region: "Coastal West Africa",
    culturalContext: "Coconut and oil palm trees along the coast",
    difficulty: "easy",
    keywords: ["movement", "actions", "warm-up"],
    illustration: { emoji: "🌴", alt: "A palm tree" },
    audio: TTS,
    activities: [
      "Do every action while the rhyme plays.",
      "Invent one new action line about a tree or an animal.",
    ],
    questions: [
      { id: "q1", prompt: "What do we do like a palm tree?", options: ["Stretch up high", "Sit down", "Sleep"], answer: "Stretch up high" },
      { id: "q2", prompt: "What wiggles like raindrops?", options: ["Fingers", "Feet", "Ears"], answer: "Fingers" },
    ],
    ...ORIGINAL,
  },
  {
    id: "ampe-jump",
    title: "Ampe Jump",
    category: "movement-actions",
    ageRange: "6–8 years",
    learningObjective: "Jump, clap and land in rhythm; count beats to three.",
    description: "A rhyme to warm up for the playground game Ampe.",
    lyrics: [
      "Jump and clap and push one foot out,",
      "Ampe time — hear the players shout!",
      "Left or right? Now match with me,",
      "Jump, clap, land — one, two, three!",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Ampe, a jumping and clapping playground game in Ghana",
    difficulty: "medium",
    keywords: ["movement", "games", "rhythm"],
    illustration: { emoji: "🤸🏾", alt: "A child jumping" },
    audio: TTS,
    activities: [
      "Play a short round of Ampe in pairs.",
      "Clap the beat of the last line: jump, clap, land.",
    ],
    questions: [
      { id: "q1", prompt: "What is Ampe?", options: ["A jumping game", "A fruit", "A song bird"], answer: "A jumping game" },
      { id: "q2", prompt: "How many beats in 'jump, clap, land'?", options: ["Three", "Two", "Five"], answer: "Three" },
    ],
    ...ORIGINAL,
  },
  {
    id: "twi-hello-words",
    title: "Twi Words for Friends",
    category: "african-languages",
    ageRange: "5–7 years",
    learningObjective: "Say and understand three everyday Twi words.",
    description: "Greeting, welcoming and thanking in Twi.",
    lyrics: [
      "Say 'Maakye' when the morning's new,",
      "'Akwaaba' means welcome — we say it to you,",
      "'Medaase' means thank you, kind and clear,",
      "Twi words for friends both far and near!",
    ],
    language: "English + Twi",
    region: "Ghana",
    culturalContext: "Akan (Twi-speaking) communities",
    difficulty: "medium",
    keywords: ["Twi", "Akan", "greetings", "language"],
    illustration: { emoji: "👋🏾", alt: "A waving hand" },
    audio: TTS,
    glossary: [
      { word: "Maakye", meaning: "Good morning" },
      { word: "Akwaaba", meaning: "Welcome" },
      { word: "Medaase", meaning: "Thank you" },
    ],
    activities: [
      "Greet three classmates with 'Maakye' and answer 'Medaase'.",
      "Make a welcome sign that says 'Akwaaba' for the classroom door.",
    ],
    questions: [
      { id: "q1", prompt: "What does 'Akwaaba' mean?", options: ["Welcome", "Goodbye", "Sorry"], answer: "Welcome" },
      { id: "q2", prompt: "How do you say 'thank you' in Twi?", options: ["Medaase", "Maakye", "Akwaaba"], answer: "Medaase" },
    ],
    ...ORIGINAL,
  },
  {
    id: "ewe-welcome-words",
    title: "Ewe Words at the Door",
    category: "african-languages",
    ageRange: "5–7 years",
    learningObjective: "Say and understand two everyday Ewe words.",
    description: "Welcoming a visitor and saying thank you in Ewe.",
    lyrics: [
      "A visitor knocks — we open wide,",
      "'Woezɔ!' we say — that's 'welcome inside!'",
      "She brings us oranges, one for each hand,",
      "'Akpe!' means thank you across Eweland.",
    ],
    language: "English + Ewe",
    region: "Volta Region, Ghana and southern Togo",
    culturalContext: "Ewe-speaking communities",
    difficulty: "medium",
    keywords: ["Ewe", "greetings", "language"],
    illustration: { emoji: "🚪", alt: "A door" },
    audio: TTS,
    glossary: [
      { word: "Woezɔ", meaning: "Welcome" },
      { word: "Akpe", meaning: "Thank you" },
    ],
    activities: [
      "Role-play a visitor arriving and use both Ewe words.",
      "Compare: how do you say 'welcome' in Twi and in Ewe?",
    ],
    questions: [
      { id: "q1", prompt: "What does 'Akpe' mean?", options: ["Thank you", "Welcome", "Good night"], answer: "Thank you" },
      { id: "q2", prompt: "What do we say to welcome the visitor?", options: ["Woezɔ", "Akpe", "Jambo"], answer: "Woezɔ" },
    ],
    ...ORIGINAL,
  },
  {
    id: "swahili-friends",
    title: "Juma's Swahili Words",
    category: "african-languages",
    ageRange: "5–7 years",
    learningObjective: "Say and understand four everyday Swahili words.",
    description: "Juma from East Africa teaches friendly words.",
    lyrics: [
      "'Jambo!' says Juma — that means hello,",
      "'Rafiki' means friend, wherever you go,",
      "'Asante' is thank you, 'Karibu' — come in!",
      "Swahili words bring a friendly grin.",
    ],
    language: "English + Swahili",
    region: "East Africa (Kenya, Tanzania, Uganda)",
    culturalContext: "Swahili-speaking communities of East Africa",
    difficulty: "medium",
    keywords: ["Swahili", "greetings", "language"],
    illustration: { emoji: "🧒🏾", alt: "A child" },
    audio: TTS,
    glossary: [
      { word: "Jambo", meaning: "Hello" },
      { word: "Rafiki", meaning: "Friend" },
      { word: "Asante", meaning: "Thank you" },
      { word: "Karibu", meaning: "Welcome / come in" },
    ],
    activities: [
      "Find East Africa on a map of Africa.",
      "Greet a partner with 'Jambo, rafiki!'",
    ],
    questions: [
      { id: "q1", prompt: "What does 'Rafiki' mean?", options: ["Friend", "Food", "Home"], answer: "Friend" },
      { id: "q2", prompt: "Where is Swahili widely spoken?", options: ["East Africa", "Only in Ghana", "Nowhere"], answer: "East Africa" },
    ],
    ...ORIGINAL,
  },
  {
    id: "atumpan-talks",
    title: "The Drum That Talks",
    category: "ghana-african-culture",
    ageRange: "6–8 years",
    learningObjective: "Explain that some drums send messages using high and low notes.",
    description: "The Akan atumpan talking drums send messages.",
    lyrics: [
      "Boom-da-da, boom! The atumpan plays,",
      "Drums that talk in the Akan ways,",
      "High notes, low notes — a message is sent,",
      "Listen closely: what was meant?",
    ],
    language: "English",
    region: "Ghana",
    culturalContext: "Akan atumpan talking drums",
    difficulty: "medium",
    keywords: ["drums", "music", "Akan", "communication"],
    illustration: { emoji: "🥁", alt: "A drum" },
    audio: TTS,
    activities: [
      "Tap a high sound and a low sound on a desk; let a partner guess which is which.",
      "Invent a two-beat 'drum message' for 'come here' and teach it to the class.",
    ],
    questions: [
      { id: "q1", prompt: "What are the drums in the rhyme called?", options: ["Atumpan", "Kente", "Ampe"], answer: "Atumpan" },
      { id: "q2", prompt: "How do talking drums send messages?", options: ["High and low notes", "Writing letters", "Colours"], answer: "High and low notes" },
    ],
    ...ORIGINAL,
  },
  {
    id: "homowo-hooting",
    title: "Hooting at Hunger",
    category: "ghana-african-culture",
    ageRange: "6–8 years",
    learningObjective: "Describe the Homowo festival and why food is shared.",
    description: "The Ga people of Accra celebrate the harvest festival Homowo.",
    lyrics: [
      "Homowo is here in Accra town,",
      "The Ga families gather all around,",
      "Kpokpoi shared with neighbour and friend,",
      "We hoot at hunger — may hunger end!",
    ],
    language: "English",
    region: "Greater Accra, Ghana",
    culturalContext: "Homowo harvest festival of the Ga people",
    difficulty: "challenging",
    keywords: ["festival", "Ga", "harvest", "sharing"],
    illustration: { emoji: "🌾", alt: "Stalks of grain" },
    audio: TTS,
    glossary: [
      { word: "Homowo", meaning: "Ga harvest festival; often explained as 'hooting at hunger'" },
      { word: "Kpokpoi", meaning: "Festival dish made from maize, eaten during Homowo" },
    ],
    activities: [
      "Talk about a festival your family celebrates and what food is shared.",
      "Draw a picture of families sharing food at a festival.",
    ],
    questions: [
      { id: "q1", prompt: "Which people celebrate Homowo?", options: ["The Ga", "The Maasai", "The Zulu"], answer: "The Ga" },
      { id: "q2", prompt: "What do families do with kpokpoi?", options: ["Share it", "Hide it", "Throw it"], answer: "Share it" },
    ],
    ...ORIGINAL,
  },
];

export function rhymesInCategory(category: RhymeCategoryId): GigaRhyme[] {
  return GIGA_RHYMES.filter((rhyme) => rhyme.category === category);
}

export function getRhyme(id: string): GigaRhyme | undefined {
  return GIGA_RHYMES.find((rhyme) => rhyme.id === id);
}

export function nextRhyme(id: string): GigaRhyme | null {
  const index = GIGA_RHYMES.findIndex((rhyme) => rhyme.id === id);
  if (index < 0 || index >= GIGA_RHYMES.length - 1) return null;
  return GIGA_RHYMES[index + 1]!;
}

/** Parse a generated rhyme (markdown from the creation engine) into a playable rhyme. */
export function parseGeneratedRhyme(
  markdown: string,
  meta: { category: RhymeCategoryId; ageRange: string; learningObjective: string; language: string; culturalContext: string }
): GigaRhyme | null {
  const title = markdown.match(/^#{1,3}\s*(?:title[:\s-]*)?(.+)$/im)?.[1]?.replace(/^title[:\s-]*/i, "").trim();
  const lyricsBlock = markdown.split(/^#{1,3}\s*lyrics\s*$/im)[1];
  if (!lyricsBlock) return null;
  const lyrics = lyricsBlock
    .split(/^#{1,3}\s/m)[0]!
    .split(/\n/)
    .map((line) => line.replace(/^\s*(?:[-*•]|\d+[.)])\s*/, "").trim())
    .filter((line) => line.length > 0 && line.length < 160)
    .slice(0, 16);
  if (lyrics.length < 2) return null;
  const category = RHYME_CATEGORIES.find((c) => c.id === meta.category);
  return {
    id: `generated-${Date.now().toString(36)}`,
    title: title || "My Giga3 Rhyme",
    category: meta.category,
    ageRange: meta.ageRange,
    learningObjective: meta.learningObjective,
    description: "Created with the GigaRhymes builder.",
    lyrics,
    language: meta.language,
    region: meta.language.match(/\(([^)]+)\)/)?.[1] ?? "",
    culturalContext: meta.culturalContext,
    difficulty: "easy",
    keywords: [],
    illustration: { emoji: category?.emoji ?? "🎵", alt: category?.label ?? "Rhyme" },
    audio: TTS,
    activities: [],
    questions: [],
    ...ORIGINAL,
  };
}
