/** Sanitize Mermaid SVG output before injecting into the DOM. */

// Note: <style> is intentionally allowed — Mermaid emits its node/edge styling
// (fills, strokes, label colors) inside an inline <style> block, and stripping
// it leaves the diagram as unstyled/invisible shapes. The style is generated by
// Mermaid from our theme config (not user input); dangerous CSS constructs are
// neutralized below. <foreignObject> stays blocked (labels use SVG <text> via
// htmlLabels:false), along with scripts and other active-content tags.
const FORBIDDEN_TAGS =
  /<\/?(script|foreignObject|iframe|object|embed|link|meta|base|form|input|button|textarea|select|option)[\s>]/gi;

const EVENT_HANDLER_ATTR = /\s+on[a-z]+\s*=/gi;
const JAVASCRIPT_URI = /\s+(href|xlink:href)\s*=\s*["']\s*javascript:/gi;
// Block CSS exfiltration / legacy JS-in-CSS vectors inside the allowed <style>.
const DANGEROUS_CSS = /@import|expression\s*\(|url\(\s*["']?\s*(?:https?:)?\/\//gi;

export function sanitizeMermaidSvg(svg: string): string {
  if (!svg.trim().startsWith("<")) return "";

  let cleaned = svg
    .replace(FORBIDDEN_TAGS, "")
    .replace(EVENT_HANDLER_ATTR, " data-blocked=")
    .replace(JAVASCRIPT_URI, " data-blocked=")
    .replace(DANGEROUS_CSS, "data-blocked(");

  if (!/^<svg[\s>]/i.test(cleaned.trim())) {
    return "";
  }

  return cleaned;
}
